os: linux
dist: bionic
language: generic
jobs:
addons:
  apt:
    update: true
services:
  - docker

before_install:
  - docker pull fr3akyphantom/droid-builder:latest
  - cd $HOME && mkdir twrp

before_script:
  - wget -q https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-7.1-norepo-20200222.tar.xz -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz

script:
  - cd $HOME/twrp/ && git clone https://github.com/LostOuija/HD65-Tree.git device/vortex/HD65
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/builder/twrp/:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw,z" fr3akyphantom/droid-builder bash << EOF
      cd /home/builder/twrp/
      source build/envsetup.sh
      # Choose build flavor as "eng" or "userdebug"
      BUILD_FLAVOR="eng"
      lunch omni_HD65-eng
      make -j$(nproc --all) recoveryimage
    EOF

after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/HD65/recovery.img $HOME/twrp/TWRP-$version-HD65-$(date +"%Y%m%d")-Unofficial.img

deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: LostOuija/HD65-Tree # Optional: If you want to deploy on different repository
    branch: master # Optional: Needs to be exact as the config branch

branches:
  only:
    - master
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
